FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

COPY backend ./backend

WORKDIR /app/backend/FloppySchnauzer.Api
RUN dotnet restore

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]
