services:
  api:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: floppy-schnauzer-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: always