version: "3.9"

services:
  backend:
    build:
      context: ./docker/dev
      dockerfile: dockerfile.dev
    volumes:
      - ./backend:/app/backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    build:
      context: ./docker/dev
      dockerfile: dockerfile.dev.frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:8080
