services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: floppy-schnauzer-api
    ports:
      - "${PORT_API}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    restart: always
    labels:
      com.floppyschnauzer.env: dev
      com.floppyschnauzer.group: platform
      com.floppyschnauzer.service: api
